const VARS = {
  ALPHA_VANTAGE_API_KEY: 'ALPHA_VANTAGE_API_KEY',

  WEB3_PROVIDER: 'WEB3_PROVIDER',
  ETH_PRIVATE_KEY: 'ETH_PRIVATE_KEY',

  CHAIN: 'CHAIN',
  GAS_LIMIT: 'GAS_LIMIT',

  // local test
  LOCAL_ORACLE_CONTRACT_ADDR: 'LOCAL_ORACLE_CONTRACT_ADDR',
};

export default VARS;
