const VARS = {
  CONSOLE_LOG: 'CONSOLE_LOG', // 'true' or 'false'

  ALPHA_VANTAGE_API_KEY: 'ALPHA_VANTAGE_API_KEY',

  WEB3_PROVIDER: 'WEB3_PROVIDER',
  ETH_PRIVATE_KEY: 'ETH_PRIVATE_KEY',

  CHAIN: 'CHAIN',
  GAS_LIMIT: 'GAS_LIMIT',

  PRICE_FEED_INTERVAL_MS: 'PRICE_FEED_INTERVAL_MS', // by milliseconds

  // local test
  LOCAL_TESTNET_ORACLE_CONTRACT_ADDR: 'LOCAL_TESTNET_ORACLE_CONTRACT_ADDR',
  FJPY: 'LOCAL_TESTNET_FJPY_ADDR',
  FEUR: 'LOCAL_TESTNET_FEUR_ADDR',
};

export default VARS;
